#!/usr/bin/env python3
"""Module that generates detailed evaluation reports."""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """Evaluate and report classification model performance.
    This report provided comprehensive summary of the model’s
    performance for each class (target variable have 3 classes)
    including: 1. precision 2. recall 3. F1-score.

    Arguments:
    true_labels: Ground truth labels
    predicted_labels: Predicted labels
    class_names: List of class names corresponding to the label indices
    Returns:
    A string containing the classification report generated by Scikit-learn.
    """
    report = metrics.classification_report(
        true_labels, predicted_labels, target_names=class_names
    )
    return report
